apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: stellarclassic-pulse-pdb
  labels:
    app: stellarclassic-pulse
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: stellarclassic-pulse
  unhealthyPodEvictionPolicy: AlwaysAllow
